### ISSUE TITLE
Membuat Halaman Dosen

### ISSUE THREAD

**Issue by nongkrek** [nongkrek/latihan-web-2020#1]
Buatlah halaman dosen menggunakan CI yang terdiri dari
- model
- view
- controller

Pada setiap bagian harus diberikan identitas nama file. Sebagai contoh bagian model, maka penamaan filenya adalah m_dosen.php

**Comment by yaddarabullah** [comment]
Tugasnya sudah selesai pak

**Comment by nongkrek** [comment]
Baik, tugas anda sudah selesai
