### ISSUE TITLE
Membuat Halaman Dosen (bagian I)

### ISSUE THREAD

**Issue by nongkrek** [nongkrek/latihan-web-2020#3]
Buatlah kode program menggunakan CI untuk menampilkan data dosen. Push kedalam branch dosen. Adapun file yang harus dipush antara lain adalah file model, view dan controller.

**Comment by yaddarabullah** [comment]
Tugas saya sudah selesai

**Comment by nongkrek** [comment]
Baik, tugas anda telah selesai
